# Generated by Django 5.2 on 2025-04-08 12:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0002_remove_advancedetail_transaction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advancedetail',
            name='datetime',
        ),
        migrations.AddField(
            model_name='advancedetail',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
