# Generated by Django 5.2 on 2025-04-10 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0004_alter_advancedetail_project_alter_inventory_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='total_buy',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='inventory',
            name='total_profit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='inventory',
            name='total_sell',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
