# Generated by Django 5.2 on 2025-04-10 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0005_inventory_total_buy_inventory_total_profit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='lifetime_advance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
